project: 
  type: website
  
website: 
  title: "Prices"
  navbar: 
    left: 
      - href: index.qmd
        text: Home
      - href: analysis.qmd
        text: Analysis
        
execute: 
  freeze: auto